version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "simpli5-backend-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oongugpgvvaa"
s3_prefix = "simpli5-backend-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
